In [1]:
%reload_ext nb_black

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import (
    Activation,
    Dropout,
    Flatten,
    Dense,
    BatchNormalization,
)
from tensorflow.keras import backend as K

<IPython.core.display.Javascript object>

In [2]:
final_df = pd.read_csv("./cleaned_data.csv")

# Converting object data to numeric data in group column
to_num = {
    "M22-": 0,
    "M23-26": 1,
    "M27-28": 2,
    "M29-31": 3,
    "M32-38": 4,
    "M39+": 5,
    "F23-": 6,
    "F24-26": 7,
    "F27-28": 8,
    "F29-32": 9,
    "F33-42": 10,
    "F43+": 11,
}

# Created new column for numeric group, can now drop old group column
final_df["num_group"] = final_df["group"].map(to_num)
final_df = final_df.drop(columns=["group"])
final_df.head()

X = final_df.drop(columns=["num_group"])
y = final_df["num_group"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=13, stratify=y
)

<IPython.core.display.Javascript object>

In [3]:
y_test

380488     9
421509     4
371406    10
3103       3
97330      5
          ..
303948     5
69371      4
241446     5
216378     5
27220      1
Name: num_group, Length: 87198, dtype: int64

<IPython.core.display.Javascript object>

In [4]:
X_test

event_id               app_id  is_active            device_id  8  9  \
380488    872832 -2339074173061010534          0  6694437260708304897  0  0   
421509   1865750  3364032031731117644          0  7740472632505276922  0  0   
371406    797469  4743373741129926453          0 -3864961701196257326  0  0   
3103         705  1919990081572238302          0 -4675255191330300693  0  0   
97330      62005  -416721070583160301          0 -5039658749766824649  0  0   
...          ...                  ...        ...                  ... .. ..   
303948    410882 -1633938282180439957          0 -3440926430976742138  0  0   
69371      36033  9136721329817567486          0  6743854432188980361  0  0   
241446    246747  6021688008523295900          0 -3901894988830598057  0  0   
216378    197200  5927333115845830913          0 -8538333663613303418  0  0   
27220      10314  3395900001236628213          0 -4469760125838724227  0  0   

        10  11  12  13  ...  device_model_魅蓝  device_model_魅蓝2  \
380488   0   0   0   0  ...                0                 0   
421509   0   0   0   0  ...                0                 0   
371406   0   0   0   0  ...                0                 0   
3103     0   0   0   0  ...                0                 0   
97330    0   0   0   0  ...                0                 0   
...     ..  ..  ..  ..  ...              ...               ...   
303948   0   0   0   0  ...                0                 0   
69371    0   0   0   0  ...                0                 0   
241446   0   0   0   0  ...                0                 0   
216378   0   0   0   0  ...                0                 0   
27220    0   0   0   0  ...                0                 0   

        device_model_魅蓝NOTE  device_model_魅蓝Note 2  device_model_魅蓝metal  \
380488                    0                      0                     0   
421509                    0                      0                     0   
371406                    0                      0                     0   
3103                      0                      0                     0   
97330                     0                      0                     0   
...                     ...                    ...                   ...   
303948                    0                      0                     0   
69371                     0                      0                     0   
241446                    0                      0                     0   
216378                    0                      0                     0   
27220                     0                      0                     0   

        device_model_麦芒3  device_model_麦芒3S  device_model_麦芒4  \
380488                 0                  0                 0   
421509                 0                  0                 0   
371406                 0                  0                 0   
3103                   0                  0                 0   
97330                  0                  0                 0   
...                  ...                ...               ...   
303948                 0                  0                 0   
69371                  0                  0                 0   
241446                 0                  0                 0   
216378                 0                  0                 0   
27220                  0                  0                 0   

        device_model_黄金斗士A8  device_model_黄金斗士Note8  
380488                    0                       0  
421509                    0                       0  
371406                    0                       0  
3103                      0                       0  
97330                     0                       0  
...                     ...                     ...  
303948                    0                       0  
69371                     0                       0  
241446                    0                       0  
216378                    0     

<IPython.core.display.Javascript object>

In [5]:
final_df.head()

event_id               app_id  is_active            device_id  8  9  10  \
0         6 -8764672938472212518          1  1476664663289716375  0  0   0   
1         6 -8271866350659046570          0  1476664663289716375  0  0   0   
2         6 -7509752927626140732          0  1476664663289716375  0  0   0   
3         6 -7377004479023402858          1  1476664663289716375  0  0   0   
4         6 -5839858269967688123          0  1476664663289716375  0  0   0   

   11  12  13  ...  device_model_魅蓝2  device_model_魅蓝NOTE  \
0   0   0   0  ...                 0                    0   
1   0   0   0  ...                 0                    0   
2   0   0   0  ...                 0                    0   
3   0   0   0  ...                 0                    0   
4   0   0   0  ...                 0                    0   

   device_model_魅蓝Note 2  device_model_魅蓝metal  device_model_麦芒3  \
0                      0                     0                 0   
1                      0                     0                 0   
2                      0                     0                 0   
3                      0                     0                 0   
4                      0                     0                 0   

   device_model_麦芒3S  device_model_麦芒4  device_model_黄金斗士A8  \
0                  0                 0                    0   
1                  0                 0                    0   
2                  0                 0                    0   
3                  0                 0                    0   
4                  0                 0                    0   

   device_model_黄金斗士Note8  num_group  
0                       0          0  
1                       0          0  
2                       0          0  
3                       0          0  
4                       0          0  

[5 rows x 635 columns]

<IPython.core.display.Javascript object>

In [6]:
final_df["num_group"].value_counts()

4     80954
5     71960
3     55421
1     50400
2     33676
10    30293
0     28706
11    23410
9     20850
6     13852
8     13659
7     12809
Name: num_group, dtype: int64

<IPython.core.display.Javascript object>

In [7]:
# Output_dim = 12 because there are 12 different age/gender groups
output_dim = 12

<IPython.core.display.Javascript object>

In [8]:
X_train_np = X_train.to_numpy()
X_test_np = X_test.to_numpy()
y_train = to_categorical(y_train, output_dim)
y_test = to_categorical(y_test, output_dim)

<IPython.core.display.Javascript object>

# 3 Layer RELU Model with ADAM Optimizer

In [9]:
model = Sequential()
model.add(Dense(128, input_dim=X_train_np.shape[1], activation="relu"))
model.add(Dense(64, activation="relu"))
model.add(Dense(12, activation="softmax"))

<IPython.core.display.Javascript object>

In [10]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

<IPython.core.display.Javascript object>

In [11]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1)

Epoch 1/20
2725/2725 [==============================] - 4s 1ms/step - loss: 7734890355228672.0000 - accuracy: 0.1148
Epoch 2/20
2725/2725 [==============================] - 4s 1ms/step - loss: 122210316451840.0000 - accuracy: 0.1795
Epoch 3/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.3080 - accuracy: 0.1857
Epoch 4/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.3080 - accuracy: 0.1857
Epoch 5/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.3080 - accuracy: 0.1857
Epoch 6/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.3080 - accuracy: 0.1857
Epoch 7/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.3080 - accuracy: 0.1857
Epoch 8/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.3080 - accuracy: 0.1857
Epoch 9/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.3080 - accuracy: 0.1857
Epoch 10/20
2725/2725 [==============================

<IPython.core.display.Javascript object>

In [12]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", score[1])

Test accuracy: 0.18568086624145508


<IPython.core.display.Javascript object>

In [26]:
y_pred = model.predict(X_test)
y_test_arg = tf.argmax(y_test, 1)
y_pred_arg = tf.argmax(y_pred, 1)

array([ 9,  4, 10, ...,  5,  5,  1], dtype=int64)

<IPython.core.display.Javascript object>

In [29]:
res = tf.math.confusion_matrix(y_test_arg, y_pred_arg)
print(res)

tf.Tensor(
[[    0     0     0     0  5741     0     0     0     0     0     0     0]
 [    0     0     0     0 10080     0     0     0     0     0     0     0]
 [    0     0     0     0  6735     0     0     0     0     0     0     0]
 [    0     0     0     0 11084     0     0     0     0     0     0     0]
 [    0     0     0     0 16191     0     0     0     0     0     0     0]
 [    0     0     0     0 14392     0     0     0     0     0     0     0]
 [    0     0     0     0  2770     0     0     0     0     0     0     0]
 [    0     0     0     0  2562     0     0     0     0     0     0     0]
 [    0     0     0     0  2732     0     0     0     0     0     0     0]
 [    0     0     0     0  4170     0     0     0     0     0     0     0]
 [    0     0     0     0  6059     0     0     0     0     0     0     0]
 [    0     0     0     0  4682     0     0     0     0     0     0     0]], shape=(12, 12), dtype=int32)


<IPython.core.display.Javascript object>

# 3 Layer RELU Model with SGD Optimizer

In [9]:
model = Sequential()
model.add(Dense(128, input_dim=X_train_np.shape[1], activation="relu"))
model.add(Dense(64, activation="relu"))
model.add(Dense(12, activation="softmax"))

<IPython.core.display.Javascript object>

In [10]:
model.compile(loss="categorical_crossentropy", optimizer="sgd", metrics=["accuracy"])

<IPython.core.display.Javascript object>

In [11]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1)

Epoch 1/20
2725/2725 [==============================] - 4s 1ms/step - loss: nan - accuracy: 0.0659
Epoch 2/20
2725/2725 [==============================] - 3s 1ms/step - loss: nan - accuracy: 0.0658
Epoch 3/20
2725/2725 [==============================] - 3s 1ms/step - loss: nan - accuracy: 0.0658
Epoch 4/20
2725/2725 [==============================] - 3s 1ms/step - loss: nan - accuracy: 0.0658
Epoch 5/20
2725/2725 [==============================] - 3s 1ms/step - loss: nan - accuracy: 0.0658
Epoch 6/20
2725/2725 [==============================] - 3s 1ms/step - loss: nan - accuracy: 0.0658
Epoch 7/20
2725/2725 [==============================] - 3s 1ms/step - loss: nan - accuracy: 0.0658
Epoch 8/20
2725/2725 [==============================] - 3s 1ms/step - loss: nan - accuracy: 0.0658
Epoch 9/20
2725/2725 [==============================] - 3s 1ms/step - loss: nan - accuracy: 0.0658
Epoch 10/20
2725/2725 [==============================] - 3s 1ms/step - loss: nan - accuracy: 0.0658
Epoch 11/

<IPython.core.display.Javascript object>

In [12]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", score[1])

Test accuracy: 0.06583866477012634


<IPython.core.display.Javascript object>

In [13]:
y_pred = model.predict(X_test)
y_test_arg = tf.argmax(y_test, 1)
y_pred_arg = tf.argmax(y_pred, 1)

<IPython.core.display.Javascript object>

In [14]:
res = tf.math.confusion_matrix(y_test_arg, y_pred_arg)
print(res)

tf.Tensor(
[[ 5741     0     0     0     0     0     0     0     0     0     0     0]
 [10080     0     0     0     0     0     0     0     0     0     0     0]
 [ 6735     0     0     0     0     0     0     0     0     0     0     0]
 [11084     0     0     0     0     0     0     0     0     0     0     0]
 [16191     0     0     0     0     0     0     0     0     0     0     0]
 [14392     0     0     0     0     0     0     0     0     0     0     0]
 [ 2770     0     0     0     0     0     0     0     0     0     0     0]
 [ 2562     0     0     0     0     0     0     0     0     0     0     0]
 [ 2732     0     0     0     0     0     0     0     0     0     0     0]
 [ 4170     0     0     0     0     0     0     0     0     0     0     0]
 [ 6059     0     0     0     0     0     0     0     0     0     0     0]
 [ 4682     0     0     0     0     0     0     0     0     0     0     0]], shape=(12, 12), dtype=int32)


<IPython.core.display.Javascript object>

# 3 Layer TANH Model with ADAM Optimizer

In [44]:
model = Sequential()
model.add(Dense(128, input_dim=X_train_np.shape[1], activation="tanh"))
model.add(Dense(64, activation="tanh"))
model.add(Dense(12, activation="softmax"))

<IPython.core.display.Javascript object>

In [45]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

<IPython.core.display.Javascript object>

In [46]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1)

Epoch 1/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3287 - accuracy: 0.1771
Epoch 2/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3141 - accuracy: 0.1824
Epoch 3/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3127 - accuracy: 0.1830
Epoch 4/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3116 - accuracy: 0.1824
Epoch 5/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3108 - accuracy: 0.1829
Epoch 6/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3104 - accuracy: 0.1833
Epoch 7/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3103 - accuracy: 0.1835
Epoch 8/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3101 - accuracy: 0.1830
Epoch 9/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.3097 - accuracy: 0.1836
Epoch 10/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.309

<IPython.core.display.Javascript object>

In [47]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", score[1])

Test accuracy: 0.18287116289138794


<IPython.core.display.Javascript object>

In [48]:
y_pred = model.predict(X_test)
y_test_arg = tf.argmax(y_test, 1)
y_pred_arg = tf.argmax(y_pred, 1)

<IPython.core.display.Javascript object>

In [49]:
res = tf.math.confusion_matrix(y_test_arg, y_pred_arg)
print(res)

tf.Tensor(
[[    0     0     0     0  4512  1229     0     0     0     0     0     0]
 [    0     1     0     0  8140  1939     0     0     0     0     0     0]
 [    0     1     0     0  5412  1322     0     0     0     0     0     0]
 [    0     0     0     0  8957  2127     0     0     0     0     0     0]
 [    0     1     0     0 13012  3178     0     0     0     0     0     0]
 [    0     0     0     0 11459  2933     0     0     0     0     0     0]
 [    0     0     0     0  2280   490     0     0     0     0     0     0]
 [    0     0     0     0  2025   537     0     0     0     0     0     0]
 [    0     0     0     0  2147   585     0     0     0     0     0     0]
 [    0     0     0     0  3360   810     0     0     0     0     0     0]
 [    0     0     0     0  4896  1163     0     0     0     0     0     0]
 [    0     0     0     0  3690   992     0     0     0     0     0     0]], shape=(12, 12), dtype=int32)


<IPython.core.display.Javascript object>

# 3 Layer TANH Model with ADAM Optimizer

In [15]:
model = Sequential()
model.add(Dense(128, input_dim=X_train_np.shape[1], activation="tanh"))
model.add(Dense(64, activation="tanh"))
model.add(Dense(12, activation="softmax"))

<IPython.core.display.Javascript object>

In [16]:
model.compile(loss="categorical_crossentropy", optimizer="sgd", metrics=["accuracy"])

<IPython.core.display.Javascript object>

In [17]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1)

Epoch 1/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.3485 - accuracy: 0.1723
Epoch 2/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.3122 - accuracy: 0.1818
Epoch 3/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3099 - accuracy: 0.1830
Epoch 4/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3089 - accuracy: 0.1829
Epoch 5/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3083 - accuracy: 0.1838
Epoch 6/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3078 - accuracy: 0.1834
Epoch 7/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3073 - accuracy: 0.1839
Epoch 8/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3070 - accuracy: 0.1841
Epoch 9/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3069 - accuracy: 0.1840
Epoch 10/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.306

<IPython.core.display.Javascript object>

In [18]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", score[1])

Test accuracy: 0.18410973250865936


<IPython.core.display.Javascript object>

In [19]:
y_pred = model.predict(X_test)
y_test_arg = tf.argmax(y_test, 1)
y_pred_arg = tf.argmax(y_pred, 1)

<IPython.core.display.Javascript object>

In [20]:
res = tf.math.confusion_matrix(y_test_arg, y_pred_arg)
print(res)

tf.Tensor(
[[    0     2     0    52  4585  1102     0     0     0     0     0     0]
 [    0     3     0   114  8110  1853     0     0     0     0     0     0]
 [    0     6     0    24  5441  1264     0     0     0     0     0     0]
 [    0     2     0   171  8793  2118     0     0     0     0     0     0]
 [    0     5     0   158 12812  3216     0     0     0     0     0     0]
 [    0     4     0    95 11225  3068     0     0     0     0     0     0]
 [    0     1     0    14  2139   616     0     0     0     0     0     0]
 [    0     1     0    31  2070   460     0     0     0     0     0     0]
 [    0     0     0    14  2276   442     0     0     0     0     0     0]
 [    0     1     0    38  3230   901     0     0     0     0     0     0]
 [    0     4     0    39  4849  1167     0     0     0     0     0     0]
 [    0     0     0    28  3853   801     0     0     0     0     0     0]], shape=(12, 12), dtype=int32)


<IPython.core.display.Javascript object>

# 3 Layer Sigmoid with ADAM Optimizer

In [56]:
model = Sequential()
model.add(Dense(128, input_dim=X_train_np.shape[1], activation="sigmoid"))
model.add(Dense(64, activation="sigmoid"))
model.add(Dense(12, activation="softmax"))

<IPython.core.display.Javascript object>

In [57]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

<IPython.core.display.Javascript object>

In [58]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1)

Epoch 1/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3119 - accuracy: 0.1822
Epoch 2/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3080 - accuracy: 0.1838
Epoch 3/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3071 - accuracy: 0.1845
Epoch 4/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3066 - accuracy: 0.1844
Epoch 5/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3061 - accuracy: 0.1845
Epoch 6/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3059 - accuracy: 0.1853
Epoch 7/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3055 - accuracy: 0.1854
Epoch 8/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3054 - accuracy: 0.1853
Epoch 9/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3052 - accuracy: 0.1851
Epoch 10/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.305

<IPython.core.display.Javascript object>

In [59]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", score[1])

Test accuracy: 0.1856120526790619


<IPython.core.display.Javascript object>

In [60]:
y_pred = model.predict(X_test)
y_test_arg = tf.argmax(y_test, 1)
y_pred_arg = tf.argmax(y_pred, 1)

<IPython.core.display.Javascript object>

In [61]:
res = tf.math.confusion_matrix(y_test_arg, y_pred_arg)
print(res)

tf.Tensor(
[[    0     0     0    23  5500   218     0     0     0     0     0     0]
 [    0     0     0    84  9585   411     0     0     0     0     0     0]
 [    0     0     0    12  6466   257     0     0     0     0     0     0]
 [    0     0     0   131 10549   404     0     0     0     0     0     0]
 [    0     0     0   113 15405   673     0     0     0     0     0     0]
 [    0     0     0    52 13691   649     0     0     0     0     0     0]
 [    0     0     0     7  2658   105     0     0     0     0     0     0]
 [    0     0     0    18  2438   106     0     0     0     0     0     0]
 [    0     0     0     6  2614   112     0     0     0     0     0     0]
 [    0     0     0    28  3971   171     0     0     0     0     0     0]
 [    0     0     0    22  5772   265     0     0     0     0     0     0]
 [    0     0     0     9  4480   193     0     0     0     0     0     0]], shape=(12, 12), dtype=int32)


<IPython.core.display.Javascript object>

# 3 Layer Sigmoid with SGD Optimizer

In [21]:
model = Sequential()
model.add(Dense(128, input_dim=X_train_np.shape[1], activation="sigmoid"))
model.add(Dense(64, activation="sigmoid"))
model.add(Dense(12, activation="softmax"))

<IPython.core.display.Javascript object>

In [22]:
model.compile(loss="categorical_crossentropy", optimizer="sgd", metrics=["accuracy"])

<IPython.core.display.Javascript object>

In [23]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1)

Epoch 1/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.3180 - accuracy: 0.1827
Epoch 2/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.3085 - accuracy: 0.1847
Epoch 3/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3080 - accuracy: 0.1847
Epoch 4/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.3077 - accuracy: 0.1850
Epoch 5/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3075 - accuracy: 0.1849
Epoch 6/20
2725/2725 [==============================] - 4s 1ms/step - loss: 2.3073 - accuracy: 0.1851
Epoch 7/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3073 - accuracy: 0.1849
Epoch 8/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3071 - accuracy: 0.1850
Epoch 9/20
2725/2725 [==============================] - 3s 1ms/step - loss: 2.3070 - accuracy: 0.1852
Epoch 10/20
2725/2725 [==============================] - 6s 2ms/step - loss: 2.306

<IPython.core.display.Javascript object>

In [24]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", score[1])

Test accuracy: 0.18549737334251404


<IPython.core.display.Javascript object>

In [25]:
y_pred = model.predict(X_test)
y_test_arg = tf.argmax(y_test, 1)
y_pred_arg = tf.argmax(y_pred, 1)

<IPython.core.display.Javascript object>

In [26]:
res = tf.math.confusion_matrix(y_test_arg, y_pred_arg)
print(res)

tf.Tensor(
[[    0     0     0     0  5587   154     0     0     0     0     0     0]
 [    0     0     0     0  9811   269     0     0     0     0     0     0]
 [    0     0     0     0  6559   176     0     0     0     0     0     0]
 [    0     0     0     0 10836   248     0     0     0     0     0     0]
 [    0     0     0     0 15790   401     0     0     0     0     0     0]
 [    0     0     0     0 14007   385     0     0     0     0     0     0]
 [    0     0     0     0  2705    65     0     0     0     0     0     0]
 [    0     0     0     0  2501    61     0     0     0     0     0     0]
 [    0     0     0     0  2665    67     0     0     0     0     0     0]
 [    0     0     0     0  4077    93     0     0     0     0     0     0]
 [    0     0     0     0  5927   132     0     0     0     0     0     0]
 [    0     0     0     0  4552   130     0     0     0     0     0     0]], shape=(12, 12), dtype=int32)


<IPython.core.display.Javascript object>

# 3 Layer RELU with ADAM Optimizer Smaller Batch Size and More Epochs

In [27]:
model = Sequential()
model.add(Dense(128, input_dim=X_train_np.shape[1], activation="relu"))
model.add(Dense(64, activation="relu"))
model.add(Dense(12, activation="softmax"))

<IPython.core.display.Javascript object>

In [28]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

<IPython.core.display.Javascript object>

In [29]:
model.fit(X_train, y_train, batch_size=64, epochs=100, verbose=1)

Epoch 1/100
5450/5450 [==============================] - 5s 928us/step - loss: 2628124579725312.0000 - accuracy: 0.1720
Epoch 2/100
5450/5450 [==============================] - 5s 933us/step - loss: 2.3080 - accuracy: 0.1857
Epoch 3/100
5450/5450 [==============================] - 5s 947us/step - loss: 2.3081 - accuracy: 0.1857
Epoch 4/100
5450/5450 [==============================] - 5s 931us/step - loss: 2.3080 - accuracy: 0.1857
Epoch 5/100
5450/5450 [==============================] - 6s 1ms/step - loss: 2.3081 - accuracy: 0.1857
Epoch 6/100
5450/5450 [==============================] - 6s 1ms/step - loss: 2.3081 - accuracy: 0.1857
Epoch 7/100
5450/5450 [==============================] - 5s 890us/step - loss: 2.3080 - accuracy: 0.1857
Epoch 8/100
5450/5450 [==============================] - 5s 977us/step - loss: 2.3080 - accuracy: 0.1857
Epoch 9/100
5450/5450 [==============================] - 5s 1ms/step - loss: 2.3080 - accuracy: 0.1857
Epoch 10/100
5450/5450 [======================

5450/5450 [==============================] - 10s 2ms/step - loss: 2.3080 - accuracy: 0.1857
Epoch 79/100
5450/5450 [==============================] - 5s 831us/step - loss: 2.3080 - accuracy: 0.1857
Epoch 80/100
5450/5450 [==============================] - 4s 822us/step - loss: 2.3080 - accuracy: 0.1857
Epoch 81/100
5450/5450 [==============================] - 5s 845us/step - loss: 2.3081 - accuracy: 0.1857
Epoch 82/100
5450/5450 [==============================] - 5s 853us/step - loss: 2.3080 - accuracy: 0.1857
Epoch 83/100
5450/5450 [==============================] - 5s 826us/step - loss: 2.3080 - accuracy: 0.1857
Epoch 84/100
5450/5450 [==============================] - 5s 827us/step - loss: 2.3080 - accuracy: 0.1857
Epoch 85/100
5450/5450 [==============================] - 8s 2ms/step - loss: 2.3080 - accuracy: 0.1857
Epoch 86/100
5450/5450 [==============================] - 6s 1ms/step - loss: 2.3080 - accuracy: 0.1857
Epoch 87/100
5450/5450 [==============================] - 5s 861

<IPython.core.display.Javascript object>

In [30]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", score[1])

Test accuracy: 0.18568086624145508


<IPython.core.display.Javascript object>

In [31]:
y_pred = model.predict(X_test)
y_test_arg = tf.argmax(y_test, 1)
y_pred_arg = tf.argmax(y_pred, 1)

<IPython.core.display.Javascript object>

In [32]:
res = tf.math.confusion_matrix(y_test_arg, y_pred_arg)
print(res)

tf.Tensor(
[[    0     0     0     0  5741     0     0     0     0     0     0     0]
 [    0     0     0     0 10080     0     0     0     0     0     0     0]
 [    0     0     0     0  6735     0     0     0     0     0     0     0]
 [    0     0     0     0 11084     0     0     0     0     0     0     0]
 [    0     0     0     0 16191     0     0     0     0     0     0     0]
 [    0     0     0     0 14392     0     0     0     0     0     0     0]
 [    0     0     0     0  2770     0     0     0     0     0     0     0]
 [    0     0     0     0  2562     0     0     0     0     0     0     0]
 [    0     0     0     0  2732     0     0     0     0     0     0     0]
 [    0     0     0     0  4170     0     0     0     0     0     0     0]
 [    0     0     0     0  6059     0     0     0     0     0     0     0]
 [    0     0     0     0  4682     0     0     0     0     0     0     0]], shape=(12, 12), dtype=int32)


<IPython.core.display.Javascript object>